# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
    
env:
  REACT_APP_DEV_API_URL: ${{secrets.REACT_APP_DEV_API_URL}}
  REACT_APP_PROD_API_URL: ${{secrets.REACT_APP_PROD_API_URL}}
  
jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Setup Node 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      # Runs a set of commands using the runners shell
      - run: npm run idependencies
      - run: npm run test
      - run: npm run build
